version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  bg:
    build:
      context: .
      dockerfile: bg/Dockerfile
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./bg:/bg']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
