version: "3.7"
services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
    volumes: ['./api:/api']

  bg:
    build:
      context: .
      dockerfile: bg/Dockerfile
    environment:
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    depends_on:
      - redis
    volumes: ['./bg:/bg']

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
